"""Schéma initial : MLD §3.2 + décisions D-01 à D-10, D-19 à D-22.

Revision ID: 0001
Revises:
Create Date: 2026-09-30 13:52:07.406961

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

CREER_PARTITIONS_VENTE = """
CREATE OR REPLACE FUNCTION creer_partitions_vente(debut date, fin date)
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
    mois date := date_trunc('month', debut)::date;
    nom text;
    nb_creees integer := 0;
BEGIN
    WHILE mois <= fin LOOP
        nom := format('vente_%s', to_char(mois, 'YYYY_MM'));
        IF to_regclass(nom) IS NULL THEN
            EXECUTE format(
                'CREATE TABLE %I PARTITION OF vente FOR VALUES FROM (%L) TO (%L)',
                nom, mois, (mois + interval '1 month')::date
            );
            nb_creees := nb_creees + 1;
        END IF;
        mois := (mois + interval '1 month')::date;
    END LOOP;
    RETURN nb_creees;
END;
$$;
"""


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calendrier",
        sa.Column("date_jour", sa.Date(), nullable=False),
        sa.Column("jour_semaine", sa.SmallInteger(), nullable=False),
        sa.Column("numero_semaine", sa.SmallInteger(), nullable=False),
        sa.Column("mois", sa.SmallInteger(), nullable=False),
        sa.Column("annee", sa.SmallInteger(), nullable=False),
        sa.Column("ferie_fr", sa.Boolean(), nullable=False),
        sa.Column("ferie_de", sa.Boolean(), nullable=False),
        sa.Column("vacances_fr", sa.Boolean(), nullable=False),
        sa.Column("vacances_de", sa.Boolean(), nullable=False),
        sa.CheckConstraint("jour_semaine BETWEEN 1 AND 7", name=op.f("ck_calendrier_jour_semaine")),
        sa.CheckConstraint("mois BETWEEN 1 AND 12", name=op.f("ck_calendrier_mois")),
        sa.PrimaryKeyConstraint("date_jour", name=op.f("pk_calendrier")),
    )
    op.create_table(
        "categorie",
        sa.Column("id_categorie", sa.Integer(), nullable=False),
        sa.Column("libelle_categorie", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id_categorie", name=op.f("pk_categorie")),
        sa.UniqueConstraint("libelle_categorie", name=op.f("uq_categorie_libelle_categorie")),
    )
    op.create_table(
        "fournisseur",
        sa.Column("id_fournisseur", sa.Integer(), nullable=False),
        sa.Column("code_fournisseur", sa.String(length=20), nullable=False),
        sa.Column("nom_fournisseur", sa.String(length=150), nullable=False),
        sa.Column("pays_fournisseur", sa.String(length=100), nullable=False),
        sa.Column("delai_moyen_jours", sa.SmallInteger(), nullable=False),
        sa.CheckConstraint("delai_moyen_jours > 0", name=op.f("ck_fournisseur_delai_moyen_jours")),
        sa.PrimaryKeyConstraint("id_fournisseur", name=op.f("pk_fournisseur")),
        sa.UniqueConstraint("code_fournisseur", name=op.f("uq_fournisseur_code_fournisseur")),
    )
    op.create_table(
        "pays",
        sa.Column("code_pays", sa.CHAR(length=2), nullable=False),
        sa.Column("nom_pays", sa.String(length=100), nullable=False),
        sa.Column("taux_tva", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("devise", sa.CHAR(length=3), nullable=False),
        sa.CheckConstraint("taux_tva >= 0 AND taux_tva < 100", name=op.f("ck_pays_taux_tva")),
        sa.PrimaryKeyConstraint("code_pays", name=op.f("pk_pays")),
    )
    op.create_table(
        "promotion",
        sa.Column("id_promotion", sa.Integer(), nullable=False),
        sa.Column("libelle", sa.String(length=200), nullable=False),
        sa.Column("date_debut", sa.Date(), nullable=False),
        sa.Column("date_fin", sa.Date(), nullable=False),
        sa.Column("taux_remise", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.CheckConstraint("date_fin >= date_debut", name=op.f("ck_promotion_dates")),
        sa.CheckConstraint(
            "taux_remise > 0 AND taux_remise < 100", name=op.f("ck_promotion_taux_remise")
        ),
        sa.PrimaryKeyConstraint("id_promotion", name=op.f("pk_promotion")),
    )
    op.create_table(
        "source_api",
        sa.Column("id_source", sa.Integer(), nullable=False),
        sa.Column("nom", sa.String(length=100), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column(
            "type_donnees",
            sa.Enum("VENTES", "STOCKS", "COMMANDES", name="type_donnees", native_enum=False),
            nullable=False,
        ),
        sa.Column("mapping_colonnes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("frequence_cron", sa.String(length=50), nullable=False),
        sa.Column("actif", sa.Boolean(), nullable=False),
        sa.Column("nom_variable_secret", sa.String(length=100), nullable=True),
        sa.CheckConstraint(
            "type_donnees IN ('VENTES', 'STOCKS', 'COMMANDES')",
            name=op.f("ck_source_api_type_donnees"),
        ),
        sa.PrimaryKeyConstraint("id_source", name=op.f("pk_source_api")),
        sa.UniqueConstraint("nom", name=op.f("uq_source_api_nom")),
    )
    op.create_table(
        "utilisateur",
        sa.Column("id_utilisateur", sa.Integer(), nullable=False),
        sa.Column("nom", sa.String(length=100), nullable=False),
        sa.Column("prenom", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("mdp_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("RESPONSABLE", "ANALYSTE", "ADMIN", name="role", native_enum=False),
            nullable=False,
        ),
        sa.Column("actif", sa.Boolean(), nullable=False),
        sa.Column("nb_echecs_connexion", sa.Integer(), nullable=False),
        sa.Column("verrouille_jusqu_a", sa.DateTime(timezone=True), nullable=True),
        sa.Column("derniere_connexion", sa.DateTime(timezone=True), nullable=True),
        sa.Column("doit_changer_mdp", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "role IN ('RESPONSABLE', 'ANALYSTE', 'ADMIN')", name=op.f("ck_utilisateur_role")
        ),
        sa.PrimaryKeyConstraint("id_utilisateur", name=op.f("pk_utilisateur")),
        sa.UniqueConstraint("email", name=op.f("uq_utilisateur_email")),
    )
    op.create_table(
        "entrepot",
        sa.Column("id_entrepot", sa.Integer(), nullable=False),
        sa.Column("code_entrepot", sa.String(length=20), nullable=False),
        sa.Column("nom_entrepot", sa.String(length=100), nullable=False),
        sa.Column("ville", sa.String(length=100), nullable=False),
        sa.Column("capacite_max", sa.Integer(), nullable=False),
        sa.Column("code_pays", sa.CHAR(length=2), nullable=False),
        sa.CheckConstraint("capacite_max > 0", name=op.f("ck_entrepot_capacite_max")),
        sa.ForeignKeyConstraint(
            ["code_pays"], ["pays.code_pays"], name=op.f("fk_entrepot_code_pays_pays")
        ),
        sa.PrimaryKeyConstraint("id_entrepot", name=op.f("pk_entrepot")),
        sa.UniqueConstraint("code_entrepot", name=op.f("uq_entrepot_code_entrepot")),
    )
    op.create_index(op.f("ix_entrepot_code_pays"), "entrepot", ["code_pays"], unique=False)
    op.create_table(
        "journal",
        sa.Column("id_log", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "date_action",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("action", sa.String(length=60), nullable=False),
        sa.Column("adresse_ip", postgresql.INET(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id_utilisateur", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_utilisateur"],
            ["utilisateur.id_utilisateur"],
            name=op.f("fk_journal_id_utilisateur_utilisateur"),
        ),
        sa.PrimaryKeyConstraint("id_log", name=op.f("pk_journal")),
    )
    op.create_index("ix_journal_action_date", "journal", ["action", "date_action"], unique=False)
    op.create_index("ix_journal_date_action", "journal", ["date_action"], unique=False)
    op.create_index(
        "ix_journal_details", "journal", ["details"], unique=False, postgresql_using="gin"
    )
    op.create_index("ix_journal_id_utilisateur", "journal", ["id_utilisateur"], unique=False)
    op.create_table(
        "produit",
        sa.Column("id_produit", sa.Integer(), nullable=False),
        sa.Column("reference", sa.String(length=20), nullable=False),
        sa.Column("libelle", sa.String(length=200), nullable=False),
        sa.Column("prix_unitaire_ht", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("seuil_alerte", sa.Integer(), nullable=False),
        sa.Column("id_categorie", sa.Integer(), nullable=False),
        sa.Column("id_fournisseur_habituel", sa.Integer(), nullable=True),
        sa.CheckConstraint("prix_unitaire_ht >= 0", name=op.f("ck_produit_prix_unitaire_ht")),
        sa.CheckConstraint("seuil_alerte >= 0", name=op.f("ck_produit_seuil_alerte")),
        sa.ForeignKeyConstraint(
            ["id_categorie"],
            ["categorie.id_categorie"],
            name=op.f("fk_produit_id_categorie_categorie"),
        ),
        sa.ForeignKeyConstraint(
            ["id_fournisseur_habituel"],
            ["fournisseur.id_fournisseur"],
            name=op.f("fk_produit_id_fournisseur_habituel_fournisseur"),
        ),
        sa.PrimaryKeyConstraint("id_produit", name=op.f("pk_produit")),
        sa.UniqueConstraint("reference", name=op.f("uq_produit_reference")),
    )
    op.create_index(op.f("ix_produit_id_categorie"), "produit", ["id_categorie"], unique=False)
    op.create_index(
        op.f("ix_produit_id_fournisseur_habituel"),
        "produit",
        ["id_fournisseur_habituel"],
        unique=False,
    )
    op.create_table(
        "synchronisation",
        sa.Column("id_synchro", sa.Integer(), nullable=False),
        sa.Column("date_debut", sa.DateTime(timezone=True), nullable=False),
        sa.Column("date_fin", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id_source", sa.Integer(), nullable=False),
        sa.Column(
            "declencheur",
            sa.Enum("CRON", "MANUEL", name="declencheur", native_enum=False),
            nullable=False,
        ),
        sa.Column("lignes_integrees", sa.Integer(), nullable=False),
        sa.Column("lignes_rejetees", sa.Integer(), nullable=False),
        sa.Column("colonnes_ignorees", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("tentatives", sa.Integer(), nullable=False),
        sa.Column(
            "statut",
            sa.Enum("EN_COURS", "SUCCES", "ECHEC_API", "ECHEC", name="statut", native_enum=False),
            nullable=False,
        ),
        sa.Column("message_erreur", sa.Text(), nullable=True),
        sa.Column("id_utilisateur", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "declencheur IN ('CRON', 'MANUEL')", name=op.f("ck_synchronisation_declencheur")
        ),
        sa.CheckConstraint(
            "statut IN ('EN_COURS', 'SUCCES', 'ECHEC_API', 'ECHEC')",
            name=op.f("ck_synchronisation_statut"),
        ),
        sa.ForeignKeyConstraint(
            ["id_source"],
            ["source_api.id_source"],
            name=op.f("fk_synchronisation_id_source_source_api"),
        ),
        sa.ForeignKeyConstraint(
            ["id_utilisateur"],
            ["utilisateur.id_utilisateur"],
            name=op.f("fk_synchronisation_id_utilisateur_utilisateur"),
        ),
        sa.PrimaryKeyConstraint("id_synchro", name=op.f("pk_synchronisation")),
    )
    op.create_index(
        "ix_synchronisation_source_debut",
        "synchronisation",
        ["id_source", "date_debut"],
        unique=False,
    )
    op.create_table(
        "commande_fournisseur",
        sa.Column("id_commande", sa.Integer(), nullable=False),
        sa.Column("numero_commande", sa.String(length=30), nullable=False),
        sa.Column("date_achat", sa.Date(), nullable=False),
        sa.Column("date_livraison_estimee", sa.Date(), nullable=False),
        sa.Column("date_livraison_reelle", sa.Date(), nullable=True),
        sa.Column(
            "statut",
            sa.Enum("EN_COURS", "LIVREE", "ANNULEE", name="statut", native_enum=False),
            nullable=False,
        ),
        sa.Column("id_fournisseur", sa.Integer(), nullable=False),
        sa.Column("id_entrepot", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "statut IN ('EN_COURS', 'LIVREE', 'ANNULEE')",
            name=op.f("ck_commande_fournisseur_statut"),
        ),
        sa.CheckConstraint(
            "date_livraison_estimee >= date_achat", name=op.f("ck_commande_fournisseur_dates")
        ),
        sa.ForeignKeyConstraint(
            ["id_entrepot"],
            ["entrepot.id_entrepot"],
            name=op.f("fk_commande_fournisseur_id_entrepot_entrepot"),
        ),
        sa.ForeignKeyConstraint(
            ["id_fournisseur"],
            ["fournisseur.id_fournisseur"],
            name=op.f("fk_commande_fournisseur_id_fournisseur_fournisseur"),
        ),
        sa.PrimaryKeyConstraint("id_commande", name=op.f("pk_commande_fournisseur")),
        sa.UniqueConstraint(
            "numero_commande", name=op.f("uq_commande_fournisseur_numero_commande")
        ),
    )
    op.create_index(
        "ix_commande_fournisseur_en_cours",
        "commande_fournisseur",
        ["id_entrepot", "date_livraison_estimee"],
        unique=False,
        postgresql_where="statut = 'EN_COURS'",
    )
    op.create_index(
        op.f("ix_commande_fournisseur_id_entrepot"),
        "commande_fournisseur",
        ["id_entrepot"],
        unique=False,
    )
    op.create_index(
        op.f("ix_commande_fournisseur_id_fournisseur"),
        "commande_fournisseur",
        ["id_fournisseur"],
        unique=False,
    )
    op.create_table(
        "kpi_quotidien",
        sa.Column("date_kpi", sa.Date(), nullable=False),
        sa.Column("id_entrepot", sa.Integer(), nullable=False),
        sa.Column("code_pays", sa.CHAR(length=2), nullable=False),
        sa.Column("nb_couples", sa.Integer(), nullable=False),
        sa.Column("nb_couples_disponibles", sa.Integer(), nullable=False),
        sa.Column("nb_sous_seuil", sa.Integer(), nullable=False),
        sa.Column("nb_ruptures_prevues", sa.Integer(), nullable=False),
        sa.Column("valeur_surstock_ht", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["code_pays"], ["pays.code_pays"], name=op.f("fk_kpi_quotidien_code_pays_pays")
        ),
        sa.ForeignKeyConstraint(
            ["id_entrepot"],
            ["entrepot.id_entrepot"],
            name=op.f("fk_kpi_quotidien_id_entrepot_entrepot"),
        ),
        sa.PrimaryKeyConstraint("date_kpi", "id_entrepot", name=op.f("pk_kpi_quotidien")),
    )
    op.create_table(
        "ligne_rejetee",
        sa.Column("id_rejet", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("id_synchro", sa.Integer(), nullable=False),
        sa.Column("numero_ligne", sa.Integer(), nullable=False),
        sa.Column("donnees", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "motif",
            sa.Enum(
                "TYPE_INVALIDE",
                "QUANTITE_NEGATIVE",
                "PRODUIT_INCONNU",
                "ENTREPOT_INCONNU",
                "DOUBLON",
                name="motif",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            "motif IN ('TYPE_INVALIDE', 'QUANTITE_NEGATIVE', 'PRODUIT_INCONNU', 'ENTREPOT_INCONNU', 'DOUBLON')",
            name=op.f("ck_ligne_rejetee_motif"),
        ),
        sa.ForeignKeyConstraint(
            ["id_synchro"],
            ["synchronisation.id_synchro"],
            name=op.f("fk_ligne_rejetee_id_synchro_synchronisation"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id_rejet", name=op.f("pk_ligne_rejetee")),
    )
    op.create_index(
        op.f("ix_ligne_rejetee_id_synchro"), "ligne_rejetee", ["id_synchro"], unique=False
    )
    op.create_table(
        "prevision",
        sa.Column("id_prevision", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("date_calcul", sa.DateTime(timezone=True), nullable=False),
        sa.Column("date_cible", sa.Date(), nullable=False),
        sa.Column("quantite_prevue", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("borne_basse", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("borne_haute", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("version_modele", sa.String(length=80), nullable=False),
        sa.Column("fiabilite_reduite", sa.Boolean(), nullable=False),
        sa.Column("id_produit", sa.Integer(), nullable=False),
        sa.Column("id_entrepot", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "borne_basse <= quantite_prevue AND quantite_prevue <= borne_haute",
            name=op.f("ck_prevision_ic"),
        ),
        sa.ForeignKeyConstraint(
            ["id_entrepot"],
            ["entrepot.id_entrepot"],
            name=op.f("fk_prevision_id_entrepot_entrepot"),
        ),
        sa.ForeignKeyConstraint(
            ["id_produit"], ["produit.id_produit"], name=op.f("fk_prevision_id_produit_produit")
        ),
        sa.PrimaryKeyConstraint("id_prevision", name=op.f("pk_prevision")),
    )
    op.create_index(
        "ix_prevision_couple_calcul",
        "prevision",
        ["id_produit", "id_entrepot", "date_calcul", "date_cible"],
        unique=False,
    )
    op.create_table(
        "produit_promotion",
        sa.Column("id_promotion", sa.Integer(), nullable=False),
        sa.Column("id_produit", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_produit"],
            ["produit.id_produit"],
            name=op.f("fk_produit_promotion_id_produit_produit"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["id_promotion"],
            ["promotion.id_promotion"],
            name=op.f("fk_produit_promotion_id_promotion_promotion"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id_promotion", "id_produit", name=op.f("pk_produit_promotion")),
    )
    op.create_table(
        "stock",
        sa.Column("id_produit", sa.Integer(), nullable=False),
        sa.Column("id_entrepot", sa.Integer(), nullable=False),
        sa.Column("quantite_stock", sa.Integer(), nullable=False),
        sa.Column("date_maj", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("quantite_stock >= 0", name=op.f("ck_stock_quantite_stock")),
        sa.ForeignKeyConstraint(
            ["id_entrepot"], ["entrepot.id_entrepot"], name=op.f("fk_stock_id_entrepot_entrepot")
        ),
        sa.ForeignKeyConstraint(
            ["id_produit"], ["produit.id_produit"], name=op.f("fk_stock_id_produit_produit")
        ),
        sa.PrimaryKeyConstraint("id_produit", "id_entrepot", name=op.f("pk_stock")),
    )
    op.create_index("ix_stock_id_entrepot", "stock", ["id_entrepot"], unique=False)
    op.create_table(
        "stock_quotidien",
        sa.Column("id_produit", sa.Integer(), nullable=False),
        sa.Column("id_entrepot", sa.Integer(), nullable=False),
        sa.Column("date_releve", sa.Date(), nullable=False),
        sa.Column("quantite_stock", sa.Integer(), nullable=False),
        sa.CheckConstraint("quantite_stock >= 0", name=op.f("ck_stock_quotidien_quantite_stock")),
        sa.ForeignKeyConstraint(
            ["date_releve"],
            ["calendrier.date_jour"],
            name=op.f("fk_stock_quotidien_date_releve_calendrier"),
        ),
        sa.ForeignKeyConstraint(
            ["id_entrepot"],
            ["entrepot.id_entrepot"],
            name=op.f("fk_stock_quotidien_id_entrepot_entrepot"),
        ),
        sa.ForeignKeyConstraint(
            ["id_produit"],
            ["produit.id_produit"],
            name=op.f("fk_stock_quotidien_id_produit_produit"),
        ),
        sa.PrimaryKeyConstraint(
            "id_produit", "id_entrepot", "date_releve", name=op.f("pk_stock_quotidien")
        ),
    )
    op.create_index(
        "ix_stock_quotidien_date_releve", "stock_quotidien", ["date_releve"], unique=False
    )
    op.create_table(
        "vente",
        sa.Column("id_vente", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("date_vente", sa.Date(), nullable=False),
        sa.Column("quantite_vendue", sa.Integer(), nullable=False),
        sa.Column("prix_vente_ht", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("id_produit", sa.Integer(), nullable=False),
        sa.Column("id_entrepot", sa.Integer(), nullable=False),
        sa.CheckConstraint("prix_vente_ht >= 0", name=op.f("ck_vente_prix_vente_ht")),
        sa.CheckConstraint("quantite_vendue >= 0", name=op.f("ck_vente_quantite_vendue")),
        sa.ForeignKeyConstraint(
            ["date_vente"], ["calendrier.date_jour"], name=op.f("fk_vente_date_vente_calendrier")
        ),
        sa.ForeignKeyConstraint(
            ["id_entrepot"], ["entrepot.id_entrepot"], name=op.f("fk_vente_id_entrepot_entrepot")
        ),
        sa.ForeignKeyConstraint(
            ["id_produit"], ["produit.id_produit"], name=op.f("fk_vente_id_produit_produit")
        ),
        sa.PrimaryKeyConstraint("id_vente", "date_vente", name=op.f("pk_vente")),
        sa.UniqueConstraint(
            "date_vente",
            "id_produit",
            "id_entrepot",
            name=op.f("uq_vente_date_vente_id_produit_id_entrepot"),
        ),
        postgresql_partition_by="RANGE (date_vente)",
    )
    op.create_index(
        "ix_vente_produit_entrepot_date",
        "vente",
        ["id_produit", "id_entrepot", "date_vente"],
        unique=False,
    )
    op.create_table(
        "alerte",
        sa.Column("id_alerte", sa.Integer(), nullable=False),
        sa.Column(
            "date_creation",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "type_alerte",
            sa.Enum(
                "SOUS_SEUIL", "RUPTURE_PREVUE", "SURSTOCK", name="type_alerte", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "statut_alerte",
            sa.Enum("OUVERTE", "TRAITEE", "IGNOREE", name="statut_alerte", native_enum=False),
            nullable=False,
        ),
        sa.Column("id_produit", sa.Integer(), nullable=False),
        sa.Column("id_entrepot", sa.Integer(), nullable=False),
        sa.Column("date_rupture_estimee", sa.Date(), nullable=True),
        sa.Column("quantite_recommandee", sa.Integer(), nullable=True),
        sa.Column("date_commande_conseillee", sa.Date(), nullable=True),
        sa.Column("motif", sa.Text(), nullable=True),
        sa.Column("id_commande", sa.Integer(), nullable=True),
        sa.Column("id_utilisateur_traitement", sa.Integer(), nullable=True),
        sa.Column("date_traitement", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "statut_alerte <> 'IGNOREE' OR (motif IS NOT NULL AND length(trim(motif)) > 0)",
            name=op.f("ck_alerte_motif_si_ignoree"),
        ),
        sa.CheckConstraint(
            "statut_alerte IN ('OUVERTE', 'TRAITEE', 'IGNOREE')",
            name=op.f("ck_alerte_statut_alerte"),
        ),
        sa.CheckConstraint(
            "type_alerte IN ('SOUS_SEUIL', 'RUPTURE_PREVUE', 'SURSTOCK')",
            name=op.f("ck_alerte_type_alerte"),
        ),
        sa.ForeignKeyConstraint(
            ["id_commande"],
            ["commande_fournisseur.id_commande"],
            name=op.f("fk_alerte_id_commande_commande_fournisseur"),
        ),
        sa.ForeignKeyConstraint(
            ["id_entrepot"], ["entrepot.id_entrepot"], name=op.f("fk_alerte_id_entrepot_entrepot")
        ),
        sa.ForeignKeyConstraint(
            ["id_produit"], ["produit.id_produit"], name=op.f("fk_alerte_id_produit_produit")
        ),
        sa.ForeignKeyConstraint(
            ["id_utilisateur_traitement"],
            ["utilisateur.id_utilisateur"],
            name=op.f("fk_alerte_id_utilisateur_traitement_utilisateur"),
        ),
        sa.PrimaryKeyConstraint("id_alerte", name=op.f("pk_alerte")),
    )
    op.create_index(
        "ix_alerte_ouvertes",
        "alerte",
        ["id_entrepot", "type_alerte"],
        unique=False,
        postgresql_where="statut_alerte = 'OUVERTE'",
    )
    op.create_index(
        "uq_alerte_ouverte_couple_type",
        "alerte",
        ["id_produit", "id_entrepot", "type_alerte"],
        unique=True,
        postgresql_where="statut_alerte = 'OUVERTE'",
    )
    op.create_table(
        "ligne_commande",
        sa.Column("id_commande", sa.Integer(), nullable=False),
        sa.Column("id_produit", sa.Integer(), nullable=False),
        sa.Column("quantite_commandee", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "quantite_commandee > 0", name=op.f("ck_ligne_commande_quantite_commandee")
        ),
        sa.ForeignKeyConstraint(
            ["id_commande"],
            ["commande_fournisseur.id_commande"],
            name=op.f("fk_ligne_commande_id_commande_commande_fournisseur"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["id_produit"],
            ["produit.id_produit"],
            name=op.f("fk_ligne_commande_id_produit_produit"),
        ),
        sa.PrimaryKeyConstraint("id_commande", "id_produit", name=op.f("pk_ligne_commande")),
    )
    op.create_index("ix_ligne_commande_id_produit", "ligne_commande", ["id_produit"], unique=False)
    # ### end Alembic commands ###

    # Partitionnement de vente (§3.3) : une partition par mois + une partition par défaut
    # (filet de sécurité : une ligne hors plage ne fait jamais échouer un import).
    # La chaîne nocturne (lot 8) appelle creer_partitions_vente() pour créer les mois à venir,
    # AVANT qu'ils ne reçoivent des lignes (sinon elles atterrissent dans vente_defaut).
    op.execute(CREER_PARTITIONS_VENTE)
    op.execute("CREATE TABLE vente_defaut PARTITION OF vente DEFAULT")
    op.execute("SELECT creer_partitions_vente(DATE '2024-01-01', CURRENT_DATE + 365)")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP FUNCTION IF EXISTS creer_partitions_vente(date, date)")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ligne_commande_id_produit", table_name="ligne_commande")
    op.drop_table("ligne_commande")
    op.drop_index(
        "uq_alerte_ouverte_couple_type",
        table_name="alerte",
        postgresql_where="statut_alerte = 'OUVERTE'",
    )
    op.drop_index(
        "ix_alerte_ouvertes", table_name="alerte", postgresql_where="statut_alerte = 'OUVERTE'"
    )
    op.drop_table("alerte")
    op.drop_index("ix_vente_produit_entrepot_date", table_name="vente")
    op.drop_table("vente")
    op.drop_index("ix_stock_quotidien_date_releve", table_name="stock_quotidien")
    op.drop_table("stock_quotidien")
    op.drop_index("ix_stock_id_entrepot", table_name="stock")
    op.drop_table("stock")
    op.drop_table("produit_promotion")
    op.drop_index("ix_prevision_couple_calcul", table_name="prevision")
    op.drop_table("prevision")
    op.drop_index(op.f("ix_ligne_rejetee_id_synchro"), table_name="ligne_rejetee")
    op.drop_table("ligne_rejetee")
    op.drop_table("kpi_quotidien")
    op.drop_index(op.f("ix_commande_fournisseur_id_fournisseur"), table_name="commande_fournisseur")
    op.drop_index(op.f("ix_commande_fournisseur_id_entrepot"), table_name="commande_fournisseur")
    op.drop_index(
        "ix_commande_fournisseur_en_cours",
        table_name="commande_fournisseur",
        postgresql_where="statut = 'EN_COURS'",
    )
    op.drop_table("commande_fournisseur")
    op.drop_index("ix_synchronisation_source_debut", table_name="synchronisation")
    op.drop_table("synchronisation")
    op.drop_index(op.f("ix_produit_id_fournisseur_habituel"), table_name="produit")
    op.drop_index(op.f("ix_produit_id_categorie"), table_name="produit")
    op.drop_table("produit")
    op.drop_index("ix_journal_id_utilisateur", table_name="journal")
    op.drop_index("ix_journal_details", table_name="journal", postgresql_using="gin")
    op.drop_index("ix_journal_date_action", table_name="journal")
    op.drop_index("ix_journal_action_date", table_name="journal")
    op.drop_table("journal")
    op.drop_index(op.f("ix_entrepot_code_pays"), table_name="entrepot")
    op.drop_table("entrepot")
    op.drop_table("utilisateur")
    op.drop_table("source_api")
    op.drop_table("promotion")
    op.drop_table("pays")
    op.drop_table("fournisseur")
    op.drop_table("categorie")
    op.drop_table("calendrier")
    # ### end Alembic commands ###
